import Figueiredo from '../../Img/rankingsPage/figueiredo.png';
import Yan from '../../Img/rankingsPage/Yan.png';
import Volkanovski from '../../Img/rankingsPage/volkanovski.png';
import Khabib from '../../Img/rankingsPage/Khabib.png';
import Usman from '../../Img/rankingsPage/usman.png';
import Adesanya from '../../Img/rankingsPage/adesanya.png';
import Blachowicz from '../../Img/rankingsPage/blachowicz.png';
import Miocic from '../../Img/rankingsPage/miocic.png';
import Weili from '../../Img/rankingsPage/weili.png';
import Valentina from '../../Img/rankingsPage/valentina.png';
import Nunes from '../../Img/rankingsPage/nunes.png';

import Brazil from '../../Img/rankingsPage/brazil.jpg';
import Russia from '../../Img/rankingsPage/russia.jpg';
import Australia from '../../Img/rankingsPage/australia.jpg';
import Usa from '../../Img/rankingsPage/usa.jpg';
import Nigeria from '../../Img/rankingsPage/nigeria.jpg';
import Poland from '../../Img/rankingsPage/poland.jpg';
import China from '../../Img/rankingsPage/china.jpg';
import Peru from '../../Img/rankingsPage/peru.jpg';


const RankingsData = [
    {
        Division: 'FLYWEIGHT',
        Img: Figueiredo,
        Flag: Brazil,
        Record: '19-1-0',
        Nr1: 'DEIVESON FIGUEIREDO',
        Nr2: 'Joseph Benavidez',
        Nr3: 'Brandon Moreno',
        Nr4: 'Askar Askarov',
        Nr5: 'Alex Perez',
        Nr6: 'Alexandre Pantoja',
        Nr7: 'Brandon Royval',
        Nr8: 'Jussier Formiga',
        Nr9: 'Kai Kara France',
        Nr10: 'Rogerio Bontorin',
        Nr11: 'Matt Schnell',
        Nr12: 'Raulian Paiva',
        Nr13: 'David Dvorak',
        Nr14: 'Tim Elliott',
        Nr15: 'Tyson Nam',
    },
    {
        Division: 'BANTAMWEIGHT',
        Flag: Russia,
        Img: Yan,
        Record: '15-1-0',
        Nr1: 'PETR YAN',
        Nr2: 'Aljamain Sterling',
        Nr3: 'Cory Sandhagen',
        Nr4: 'Marlon Moraes',
        Nr5: 'Cody Garbrandt',
        Nr6: 'Frankie Edgar',
        Nr7: 'Pedro Munhoz',
        Nr8: 'Jose Aldo',
        Nr9: 'Jimmie Rivera',
        Nr10: 'Raphael Assuncao',
        Nr11: 'Dominick Cruz',
        Nr12: 'Rob Font',
        Nr13: 'Cody Stamann',
        Nr14: 'Merab Dvalishvili',
        Nr15: 'Song Yadong',
    },
    {
        Division: 'FEATHERWEIGHT',
        Flag: Australia,
        Img: Volkanovski,
        Record: '22-1-0',
        Nr1: 'ALEXANDER VOLKANOVSKI',
        Nr2: 'Max Holloway',
        Nr3: 'Brian Ortega',
        Nr4: 'Zabit Magomedsharipov',
        Nr5: 'Yair Rodriguez',
        Nr6: 'Chan Sung Jung',
        Nr7: 'Calvin Kattar',
        Nr8: 'Josh Emmett',
        Nr9: 'Jeremy Stephens',
        Nr10: 'Arnold Allen',
        Nr11: 'Sodiq Yusuff',
        Nr12: 'Shane Burgos',
        Nr13: 'Dan Ige',
        Nr14: 'Ryan Hall',
        Nr15: 'Edson Barboza',
    },
    {
        Division: 'LIGHTWEIGHT',
        Flag: Russia,
        Img: Khabib,
        Record: '28-0-0',
        Nr1: 'KHABIB NURMAGOMEDOV',
        Nr2: 'Justin Gaethje',
        Nr3: 'Dustin Poirier',
        Nr4: 'Tony Ferguson',
        Nr5: 'Conor McGregor',
        Nr6: 'Dan Hooker',
        Nr7: 'Charles Oliveira',
        Nr8: 'Paul Felder',
        Nr9: 'Diego Ferreira',
        Nr10: 'Al Iaquinta',
        Nr11: 'Kevin Lee',
        Nr12: 'Beneil Dariush',
        Nr13: 'Islam Makhachev',
        Nr14: 'Gregor Gillespie',
        Nr15: 'Drew Dober',
    },
    {
        Division: 'WELTERWEIGHT',
        Flag: Usa,
        Img: Usman,
        Record: '17-1-0',
        Nr1: 'KAMARU USMAN',
        Nr2: 'Colby Covington',
        Nr3: 'Gilbert Burns',
        Nr4: 'Leon Edwards',
        Nr5: 'Jorge Masvidal',
        Nr6: 'Stephen Thompson',
        Nr7: 'Demian Maia',
        Nr8: 'Tyron Woodley',
        Nr9: 'Michael Chiesa',
        Nr10: 'Neil Magny',
        Nr11: 'Vicente Luque',
        Nr12: 'Geoff Neal',
        Nr13: 'Rafael Dos Anjos',
        Nr14: 'Nate Diaz',
        Nr15: 'Anthony Pettis',
    },
    {
        Division: 'MIDDLEWEIGHT',
        Flag: Nigeria,
        Img: Adesanya,
        Record: '19-0-0',
        Nr1: 'ISRAEL ADESANYA',
        Nr2: 'Robert Whittaker',
        Nr3: 'Jared Cannonier',
        Nr4: 'Paulo Costa',
        Nr5: 'Jack Hermansson',
        Nr6: 'Yoel Romero',
        Nr7: 'Darren Till',
        Nr8: 'Derek Brunson',
        Nr9: 'Kelvin Gastelum',
        Nr10: 'Chris Weidman',
        Nr11: 'Uriah Hall',
        Nr12: 'Edmen Shahbazyan',
        Nr13: 'Brad Tavares',
        Nr14: 'Omari Akhmedov',
        Nr15: 'Marvin Vettori',
    },
    {
        Division: 'LIGHT HEAVYWEIGHT',
        Flag: Poland,
        Img: Blachowicz,
        Record: '27-8-0',
        Nr1: 'JAN BŁACHOWICZ',
        Nr2: 'Thiago Santos',
        Nr3: 'Dominick Reyes',
        Nr4: 'Glover Teixeira',
        Nr5: 'Aleksandar Rakic',
        Nr6: 'Jiri Prochazka',
        Nr7: 'Volkan Oezdemir',
        Nr8: 'Anthony Smith',
        Nr9: 'Nikita Krylov',
        Nr10: 'Johnny Walker',
        Nr11: 'Misha Cirkunov',
        Nr12: 'Magomed Ankalaev',
        Nr13: 'Ryan Spann',
        Nr14: 'Jim Crute',
        Nr15: 'Mauricio Rua',
    },
    {
        Division: 'HEAVYWEIGHT',
        Flag: Usa,
        Img: Miocic,
        Record: '20-3-0',
        Nr1: 'STIPE MIOCIC',
        Nr2: 'Francis Ngannou',
        Nr3: 'Curtis Blaydes',
        Nr4: 'Jairzinho Rozenstruik',
        Nr5: 'Derrick Lewis',
        Nr6: 'Alistair Overeem',
        Nr7: 'Junior Dos Santos',
        Nr8: 'Alexander Volkov',
        Nr9: 'Augusto Sakai',
        Nr10: 'Shamil Abdurakhimov',
        Nr11: 'Walt Harris',
        Nr12: 'Aleksei Oleinik',
        Nr13: 'Sergei Pavlovich',
        Nr14: 'Ciryl Gane',
        Nr15: 'Blagoy Ivanov',
    },
    {
        Division: "WOMEN'S STRAWWEIGHT",
        Flag: China,
        Img: Weili,
        Record: '21-1-0',
        Nr1: 'WEILI ZHANG',
        Nr2: 'Rose Namajunas',
        Nr3: 'Joanna Jedrzejczyk',
        Nr4: 'Jessica Andrade',
        Nr5: 'Carla Esparza',
        Nr6: 'Claudia Gadelha',
        Nr7: 'Nina Ansaroff',
        Nr8: 'Michelle Waterson',
        Nr9: 'Marina Rodriguez',
        Nr10: 'Yan Xiaonan',
        Nr11: 'Amanda Ribas',
        Nr12: 'Tecia Torres',
        Nr13: 'Mackenzie Dern',
        Nr14: 'Angela Hill',
        Nr15: 'Virna Jandiroba',
    },
    {
        Division: "WOMEN'S FLYWEIGHT",
        Flag: Peru,
        Img: Valentina,
        Record: '19-3-0',
        Nr1: 'VALENTINA SHEVCHENKO',
        Nr2: 'Jessica Andrade',
        Nr3: 'Katlyn Chookagian',
        Nr4: 'Jennifer Maia',
        Nr5: 'Cynthia Calvillo',
        Nr6: 'Lauren Murphy',
        Nr7: 'Jessica Eye',
        Nr8: 'Joanne Calderwood',
        Nr9: 'Roxanne Modafferi',
        Nr10: 'Viviane Araujo',
        Nr11: 'Andrea Lee',
        Nr12: 'Maycee Barber',
        Nr13: 'Gillian Robertson',
        Nr14: 'Alexis Davis',
        Nr15: 'Montana De La Rosa',
    },
    {
        Division: "WOMEN'S BANTAMWEIGHT",
        Flag: Brazil,
        Img: Nunes,
        Record: '20-4-0',
        Nr1: 'AMANDA NUNES',
        Nr2: 'Germaine De Randamie',
        Nr3: 'Holly Holm',
        Nr4: 'Aspen Ladd',
        Nr5: 'Raquel Pennington',
        Nr6: 'Irene Aldana',
        Nr7: 'Julianna Peña',
        Nr8: 'Ketlen Vieira',
        Nr9: 'Yana Kunitskaya',
        Nr10: 'Sara McMann',
        Nr11: 'Marion Reneau',
        Nr12: 'Lina Lansberg',
        Nr13: 'Macy Chiasson',
        Nr14: 'Sijara Eubanks',
        Nr15: 'Pannie Kianzad',
    },
]

export default RankingsData; 